# Generated by Django 3.1.2 on 2020-11-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0004_auto_20201021_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='password',
        ),
    ]
