# Generated by Django 3.1.2 on 2020-12-16 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0005_auto_20201105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
